include:
  - board: nice_nano_v2
    shield: dactyl_manuform_6x7_left nice_oled
  - board: nice_nano_v2
    shield: dactyl_manuform_6x7_right nice_oled
  - board: nice_nano_v2
    shield: settings_reset
